/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#7d2800",
        "on-primary-fixed": "#002117",
        "surface-dim": "#d9dad7",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#002204",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#88d982",
        "primary-fixed": "#baeed9",
        "outline-variant": "#c0c9c3",
        "surface-container": "#edeeea",
        "outline": "#707974",
        "on-primary-fixed-variant": "#1d4f40",
        "surface-container-highest": "#e2e3df",
        "on-error-container": "#93000a",
        "on-surface-variant": "#404945",
        "error-container": "#ffdad6",
        "on-surface": "#1a1c1a",
        "surface-container-low": "#f3f4f0",
        "background": "#f9faf6",
        "on-secondary-container": "#217128",
        "on-primary-container": "#8abda9",
        "on-background": "#1a1c1a",
        "on-secondary-fixed-variant": "#005312",
        "inverse-primary": "#9ed1bd",
        "surface-container-high": "#e7e9e5",
        "surface": "#f9faf6",
        "surface-bright": "#f9faf6",
        "secondary-fixed": "#a3f69c",
        "tertiary-fixed-dim": "#ffb59a",
        "on-tertiary": "#ffffff",
        "secondary": "#1b6d24",
        "tertiary": "#571a00",
        "primary-fixed-dim": "#9ed1bd",
        "secondary-container": "#a0f399",
        "primary-container": "#1b4d3e",
        "on-secondary": "#ffffff",
        "surface-tint": "#376757",
        "inverse-on-surface": "#f0f1ed",
        "on-tertiary-fixed-variant": "#802a00",
        "on-tertiary-container": "#ff976f",
        "inverse-surface": "#2e312f",
        "tertiary-fixed": "#ffdbcf",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary": "#003629",
        "on-tertiary-fixed": "#380d00",
        "surface-variant": "#e2e3df"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "gutter": "1rem",
        "space-md": "1rem",
        "gutter-tablet": "1.5rem",
        "space-sm": "0.5rem",
        "margin": "1rem",
        "margin-desktop": "3rem",
        "space-xl": "2.5rem",
        "gutter-desktop": "2rem",
        "margin-tablet": "2rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "18px", letterSpacing: "0.03em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "500" }],
        "label-lg": ["16px", { lineHeight: "22px", letterSpacing: "0.02em", fontWeight: "700" }]
      }
    }
  },
  plugins: [],
}
